#!/usr/bin/env bash
# Interactive first-time setup for the compose stack.
#
# Asks for the names (usernames, database, admin email), GENERATES every
# password and key — nobody should be inventing a 32-byte sealing key by
# hand — and writes the result to deploy/compose/.env, which git ignores.
#
# Idempotent by refusal: an existing .env is never overwritten without an
# explicit yes, because regenerating credentials does not update an already
# initialised Postgres volume or re-seal enrolled MFA secrets.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/deploy/compose/.env"

# ---------------------------------------------------------------- generators
# Alphanumeric only for values that end up inside a DSN: characters like
# @ / : ? would need URL-encoding and quietly break the connection string.
gen_alnum() { # <length>
    # A bounded read first: an unbounded tr feeding head dies of SIGPIPE
    # under pipefail. 1 KiB of randomness always yields enough alnum chars.
    head -c 1024 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | head -c "$1"
}
# base64url of N random bytes: no padding, URL- and env-safe.
gen_b64() { # <bytes>
    openssl rand -base64 "$1" | tr '+/' '-_' | tr -d '=\n'
}

ask() { # <prompt> <default> -> stdout
    local answer
    read -r -p "$1 [$2]: " answer
    printf '%s' "${answer:-$2}"
}

# ---------------------------------------------------------------- guard
if [ -f "$ENV_FILE" ]; then
    echo "WARNING: $ENV_FILE already exists."
    echo "Regenerating credentials will NOT update an initialised Postgres volume"
    echo "or re-seal MFA secrets already enrolled under the old key."
    read -r -p "Overwrite it? [y/N]: " confirm
    case "$confirm" in
        y|Y|yes|YES) ;;
        *) echo "Keeping the existing file."; exit 0 ;;
    esac
fi

echo "== SIEM v2 compose setup =="
echo "Names are asked; every password and key is generated."
echo

PG_USER=$(ask "PostgreSQL username" "siem")
PG_DB=$(ask "PostgreSQL database" "siem")
S3_ACCESS=$(ask "Object-store access key (username-like)" "siem")
ADMIN_EMAIL=$(ask "Bootstrap administrator email" "admin@siem.local")
CONSOLE_ORIGIN=$(ask "Console origin the browser will use" "http://localhost:3002")
API_BASE=$(ask "API base the browser will call" "http://localhost:8000/api/v1")
INGEST_BASE=$(ask "Ingest base shown in copy-paste URLs" "http://localhost:8100")

echo
echo "Generating secrets…"
PG_PASSWORD=$(gen_alnum 32)
S3_SECRET=$(gen_alnum 40)
INGEST_SECRET=$(gen_b64 32)
JWT_KEY=$(gen_b64 48)      # 64 chars, comfortably past the 32-byte floor
MFA_KEY=$(gen_alnum 32)    # EXACTLY 32 bytes — the sealer refuses anything else

[ "${#MFA_KEY}" -eq 32 ] || { echo "ERROR: MFA key generation produced ${#MFA_KEY} bytes"; exit 1; }

# ---------------------------------------------------------------- write
umask 077
cat > "$ENV_FILE" <<ENV
# Generated by setup.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ') — git ignores this file.
# Regenerating does NOT update an initialised Postgres volume or re-seal
# enrolled MFA secrets; see .env.example for what each variable does.

# -------------------------------------------------- credentials (infra)
SIEM_PG_USER=$PG_USER
SIEM_PG_PASSWORD=$PG_PASSWORD
SIEM_PG_DB=$PG_DB
SIEM_S3_ACCESS_KEY=$S3_ACCESS
SIEM_S3_SECRET_KEY=$S3_SECRET

# -------------------------------------------------- app profile
SIEM_JWT_KEY=$JWT_KEY
SIEM_MFA_KEY=$MFA_KEY
SIEM_INGEST_SECRET=$INGEST_SECRET
SIEM_CORS_ORIGINS=$CONSOLE_ORIGIN
SIEM_ADMIN_EMAIL=$ADMIN_EMAIL
NUXT_PUBLIC_API_BASE=$API_BASE
NUXT_PUBLIC_INGEST_BASE=$INGEST_BASE

# -------------------------------------------------- optional
# Cloudflare Tunnel token, only read by: docker compose --profile tunnel up
CLOUDFLARE_TUNNEL_TOKEN=
ENV

echo
echo "Wrote $ENV_FILE (mode 600)."
echo
echo "Next steps:"
echo "  docker compose -f deploy/compose/docker-compose.yml --profile app up -d --build"
echo "  docker compose -f deploy/compose/docker-compose.yml logs apiserver | grep BOOTSTRAP"
echo
echo "The BOOTSTRAP log line carries the one-time setup link for $ADMIN_EMAIL."
echo "Passwords and keys live only in $ENV_FILE — treat the file as the secret."
