# syntax=docker/dockerfile:1
FROM rust:1-slim AS build
WORKDIR /src
COPY wirefilter-svc/Cargo.toml wirefilter-svc/Cargo.lock ./
COPY wirefilter-svc/src ./src
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12:nonroot
COPY --from=build /src/target/release/wirefilter-svc /wirefilter-svc
USER nonroot:nonroot
EXPOSE 8081
ENTRYPOINT ["/wirefilter-svc"]
